<tr>
    <td><a href='<?= $this->baseUrl()?>/acard/movimenti/codcliente/<?= $this->codcliente; ?>'><?= $this->codcliente; ?></a></td>
    <td><a href='<?= $this->baseUrl()?>/acard/movimenti/codcliente/<?= $this->codcliente; ?>'><?= $this->ragionesociale; ?></a></td>
    <td><?= $this->datanascita; ?></td>
    <td><?= $this->sesso; ?></td>
    <td><a href='<?= $this->baseUrl()?>/acard/movimenti/ncard/<?= $this->ncard; ?>'><?= $this->ncard; ?></a></td>
    <td><?= $this->puntovendita; ?></td>
    <td><?= $this->codcassa; ?></td>
    <td><?= $this->nscontrino; ?></td>
    <td><?= $this->dataoraacquisto; ?></td>
    <td><?= $this->importo; ?></td>
    <td><?= $this->dataoratransazione; ?></td>
    <td><?= $this->puntiassegnati; ?></td>
<tr>